updates to make clear root can be catalog or collection
radiantearth/stac-spec pull request #1091
Opened 2021-04-20 04:07 UTC by cholmes

**Related Issue(s):** #1082 

**Proposed Changes:**

1. Various little tweaks to make it clear that the 'root' can be a Catalog or Collection
2. Or small language tightening that came up as reading.

**PR Checklist:**

- [x] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [x] This PR has **no** breaking changes.
- [x]  a CHANGELOG entry is not required.

2021-04-20 13:14 UTC, m-mohr commented on overview.md
> +is simply the top-most Catalog -- it has no parent. A nested catalog structure is useful (and
```suggestion
is simply the top-most Catalog or Collection -- it has no parent. A nested catalog structure is useful (and
```

2021-04-20 13:16 UTC, m-mohr commented on overview.md
> +*NOTE: The above examples all say Catalog, but those can all be Collections as well, as it has all the fields necessary to
Maybe put at the top where it starts to get important to say this? May reduce confusion...

2021-04-20 13:23 UTC, m-mohr commented
There are a lot more things to change, for example, numerous mentions of Catalogs in Best Practices, which should always mention both Catalogs and Collections.

The item spec also has a mention of "root Catalog" in the description of the ID field.

2021-04-20 13:25 UTC, m-mohr requested changes
There are more things to change, for example, numerous mentions of Catalogs in Best Practices, which should always mention both Catalogs and Collections.

The item spec also has a mention of "root Catalog" in the description of the ID field.

2021-04-20 15:41 UTC, jbants approved these changes

2021-04-20 17:01 UTC, matthewhanson approved these changes

2021-04-21 15:42 UTC, jisantuc approved these changes

2021-04-23 13:20 UTC, m-mohr commented
Some more parts, which seem to apply to both Catalog and Collection:

### best-practices (I haven't read it completely):

> Sub-Catalogs should be stored in subdirectories of their parent

> Items should be stored in subdirectories of their parent Catalog. 

> Limit the number of Items in a Catalog or sub-Catalog, grouping / partitioning as relevant to the dataset.

> providing multiple 'sub-catalogs'
> from the root Catalog that enable different paths to browse

> This is a self-contained catalog as described above, except it includes an absolute `self` link at
> the root catalog

### catalog-spec:

> Every STAC Collection is 
> also a valid STAC Catalog.

Not true in validation due to the type field.

> **Note:** A link to at least one `item` or `child` Catalog is **REQUIRED**.

One child link is required, can be Catalog or Collection.

### collection-spec:

> Summaries should summarize all values in every Item underneath the collection, including in any nested sub-Catalogs.

> | parent  | URL to the parent STAC entity (Catalog or Collection). Non-root Collections should include a link to their parent. |
> | child   | URL to a child STAC Catalog or Collection. |

Why is it sometimes "STAC entity (Catalog or Collection)" and sometimes "STAC Catalog or Collection"?

2021-04-23 14:18 UTC, cholmes commented
Weird, I had a couple of those on my local copy but didn't get them committed. Will do the rest and commit.

2021-04-23 14:28 UTC, cholmes commented
I think I got them all.

2021-04-23 14:36 UTC, m-mohr approved these changes
Approving after a couple of additional changes, please check them @cholmes and then you can merge.

2021-04-23 16:02 UTC, merged