Fix a missing pluralization
radiantearth/stac-spec pull request #1201
Opened 2022-11-30 22:45 UTC by kurtmckee

**Related Issue(s):** N/A

**Proposed Changes:**

1. Fixed a missing 's' on the word "providers".

   `providers` is an array so this sentence only makes sense if the ID is unique across all of the listed providers (plural).

**PR Checklist:**

- [x] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [x] This PR has **no** breaking changes.
- [x] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md)
      **or** a CHANGELOG entry is not required.
- [ ] This PR affects the [STAC API spec](https://github.com/radiantearth/stac-api-spec),
      and I have opened issue/PR #XXX to track the change.

2022-12-06 10:13 UTC, m-mohr approved these changes

2023-01-05 10:57 UTC, m-mohr requested changes
Looking at this again, I'm not sure this is actually correct. You can only verify the ID is unique across what you as a provider have control over. You can't control this for all providers.

2023-01-09 21:54 UTC, m-mohr commented
Thank you for the PR. We discussed it in the STAC PSC meeting today and came to the conclusion that both "provider" and "providers" is ambiguous and thus we drafted a new wording that hopefully is more clear. See PR #1209 for details.

2023-01-09 21:54 UTC, closed without merging

2023-01-14 20:46 UTC, kurtmckee commented
Thanks Matthias!