Keywords in common metadata
radiantearth/stac-spec pull request #1227
Opened 2023-04-13 10:14 UTC by emmanuelmathot

**Related Issue(s):** #1187

**Proposed Changes:**

1. Keywords fields in common metadata to have it available in Stac Item 

**PR Checklist:**

- [X] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [X] This PR has **no** breaking changes.
- [X] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md)
      **or** a CHANGELOG entry is not required.
- [ ] This PR affects the [STAC API spec](https://github.com/radiantearth/stac-api-spec),
      and I have opened issue/PR #XXX to track the change.

2023-04-13 10:17 UTC, m-mohr requested changes
Thanks. The collection should still have keywords, just referenced from the common metadata. So no change in Collections except that the schema lives somewhere else.

2023-04-13 10:19 UTC, emmanuelmathot commented
isn't it included automatically with the common metadata inclusion?

https://github.com/radiantearth/stac-spec/blob/92161e4424ad59fbadb29e4d21c1efaa55a6216f/collection-spec/json-schema/collection.json#L11

2023-04-13 10:22 UTC, m-mohr commented
Good point, I'll check...

2023-04-25 10:18 UTC, m-mohr commented
@cholmes @matthewhanson Would someone be willing to review this?

2023-06-06 19:15 UTC, merged