updated changelog
radiantearth/stac-spec pull request #1323
Opened 2024-09-08 15:49 UTC by emmanuelmathot

**Related Issue(s):** #

**Proposed Changes:**

1. Update version numbers to v1.1.0

**PR Checklist:**

- [X] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [X] This PR has **no** breaking changes.
- [X] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md)
      **or** a CHANGELOG entry is not required.
- [ ] This PR affects the [STAC API spec](https://github.com/radiantearth/stac-api-spec),
      and I have opened issue/PR #XXX to track the change.

2024-09-08 16:40 UTC, m-mohr commented on CITATION.cff
> +  date-released: 2024-09-08
```suggestion
  date-released: 2024-09-10
```
As we'll probably not release today

2024-09-08 16:40 UTC, m-mohr commented on CHANGELOG.md
> +## [v1.1.0] - 2024-09-08
```suggestion
## [v1.1.0] - 2024-09-10
```

2024-09-08 16:41 UTC, m-mohr requested changes
We should probably release eo and raster first and also update the version numbers (removing the -beta.1) of those extensions?!

2024-09-09 15:20 UTC, jbants approved these changes

2024-09-09 22:16 UTC, m-mohr commented on CHANGELOG.md
> +[v1.1.0]: <https://github.com/radiantearth/stac-spec/compare/v1.1.0-beta.1...v1.1.0>
```suggestion
[Unreleased]: <https://github.com/radiantearth/stac-spec/compare/master...dev>
[v1.1.0]: <https://github.com/radiantearth/stac-spec/compare/v1.1.0-beta.1...v1.1.0>
```

2024-09-09 22:16 UTC, m-mohr commented on CHANGELOG.md
> +## [v1.1.0] - 2024-09-10
```suggestion
## [Unreleased]

## [v1.1.0] - 2024-09-10
```

2024-09-09 22:18 UTC, merged