Modify valid range for sun_elevation to be -90-90.
radiantearth/stac-spec pull request #919
Opened 2020-11-21 14:25 UTC by lossyrob

Fixes #853

**Related Issue(s):** #853

**Proposed Changes:**

As mentioned in #853, a negative view angle can be validly recorded in remove sensing data. Besides the example listed by the issue author, I've hit up against this in ASTER L1T data, in which the [product specification](https://lpdaac.usgs.gov/documents/300/ASTER_L1T_Product_Specification.pdf) states values will range from -90 to 90, and a many of the images record such a value in the HDF metadata.

This change modifies the spec text and JSON schema to allow for sun_elevation values ranging from -90 to 90.

**PR Checklist:**

- [x] This PR is made against the dev branch (all proposed changes except releases should be against dev, not master).
- [x] This PR has **no** breaking changes.
- [ ] I have added my changes to the [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/dev/CHANGELOG.md) **or** a CHANGELOG entry is not required.
- [ ] ~~This PR affects the [STAC API spec](https://github.com/radiantearth/stac-api-spec), and I have opened issue/PR #XXX to track the change.~~

2020-11-23 03:13 UTC, matthewhanson commented
+1 on this, it's come up several times. Most users will consider the absolute value, but the +/- will indicate port/starboard depending on platform.

2020-11-23 03:13 UTC, matthewhanson approved these changes

2020-11-23 07:18 UTC, m-mohr commented on extensions/view/README.md
> +| view:sun_elevation   | number               | Sun elevation angle. The angle from the tangent of the scene center point to the sun. Measured from the horizon in degrees (-90-90). |
The -90-90 looks a bit strange, maybe put spaces?

```suggestion
| view:sun_elevation   | number               | Sun elevation angle. The angle from the tangent of the scene center point to the sun. Measured from the horizon in degrees (-90 - 90). |
```

2020-11-23 07:24 UTC, m-mohr commented
I agree with @cholmes https://github.com/radiantearth/stac-spec/issues/853#issuecomment-645585134 that it feels like it is overloading the view angle as it may not be intuitively clear what a negative value could mean and maybe it should be considered go with an (additional?) and more general `view:night: true/false` or so. But as this seems to be used across multiple providers, it might also just be a best practice that has been established for night shots to just use negative values and then I think it's fine. 🤷‍♀️

2020-11-23 07:25 UTC, m-mohr requested changes
A bit more explanation on what negative values mean should be added.

2020-11-30 17:10 UTC, cholmes commented
I'm ok with the negative value, since it looks like you're seeing it across multiple providers @lossyrob but I agree with Matthias that we should add a bit of explanation in the table that a negative value means it was taken at night.

2020-12-01 20:49 UTC, matthewhanson commented
Not sure why I didn't remember this before, but I ended up re-implementing the solar angle calculation in the processing of ASTER L1 for LPDAAC a few years ago in Cumulus, so I'm familiar with this particular case. It was using old FORTRAN code that was last updated in 1997, and I switched to using [Skyfield](https://rhodesmill.org/skyfield/).

But to the point...

A negative sun elevation does not necessarily mean "night", or at least it depends on your definition of "night".  The most accepted definitions are:
![image](https://user-images.githubusercontent.com/1416900/100795182-a34d9080-33ec-11eb-8000-2ba3e86917a2.png)


ASTER has a day/night flag, and it defines night as astronomical twilight, so 12 degrees below the horizon.

2020-12-11 17:20 UTC, cholmes commented
@lossyrob - can you add a bit more explanation on negative values? What they mean? Doesn't have to be a lot. If not I can take a crack at it, but it'd be good to get this merged in.

2020-12-11 18:04 UTC, lossyrob commented
@cholmes thanks for the ping. @m-mohr does the additional text work for additional explanation?

2021-01-18 22:30 UTC, m-mohr approved these changes
I'm neutral on this change and can't say whether it's a good solution or not, but I have to approve after requesting changes. So better get another opinion on this one. Was @matthewhanson's comment considered?

2021-01-19 23:52 UTC, matthewhanson commented
I think this is a necessary change but think we should expand on "this data was captured at night" because "night" isn't really a boolean by itself.  Suggest updating text to be:

Negative values indicate the sun is below the horizon, e.g. sun elevation of -10&deg; means the data was captured during [nautical twilight or dawn](https://www.timeanddate.com/astronomy/different-types-twilight.html).

Including the link provides users a simple and concise explanation of night vs day.

2021-02-02 15:51 UTC, lossyrob commented
@matthewhanson included your example and the link, if good by you then merge away!

2021-02-03 17:35 UTC, cholmes approved these changes

2021-02-03 17:35 UTC, merged